# .circleci/config.yml file
version: 2.1

jobs:
  build:            # job name
    docker:         # executor type
      - image: cimg/base:current # Docker image that installs Docker and has Git,
      - image: cimg/node:12.0
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - run:
          name: Build and push Docker image
          command: |
            # Build
            docker-compose -f docker-compose-build.yaml build --parallel
            # Tagging
            docker tag udagram-api-feed hesticide/udagram-api-feed:latest
            docker tag udagram-api-user hesticide/udagram-api-user:latest
            docker tag udagram-frontend hesticide/udagram-frontend:latest
            docker tag reverseproxy hesticide/reverseproxy:latest
            # Log info
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            # Push
            docker push hesticide/udagram-api-feed
            docker push hesticide/udagram-api-user
            docker push hesticide/udagram-frontend
            docker push hesticide/reverseproxy
